# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

# encoding: utf-8

Category.create([
  { :description => "Base de Datos", :created_at => "2013-07-17 00:18:01", :updated_at => "2013-07-17 00:18:01" },
  { :description => "Diseño Grafico", :created_at => "2013-07-17 00:18:23", :updated_at => "2013-07-17 00:18:23" },
  { :description => "Modelamiento", :created_at => "2013-07-17 00:18:54", :updated_at => "2013-07-17 00:18:54" }
], :without_protection => true )


# encoding: utf-8

Computer.create([
  { :ram => nil, :processor => nil, :motherboard => nil, :display => nil, :mouse => nil, :keyboard => nil, :videocard => nil, :laboratory_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )


# encoding: utf-8

Course.create([
  { :code => "201001", :name => "Algoritmica I", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:49:08", :updated_at => "2013-06-26 17:49:08" },
  { :code => "201008", :name => "Computación Informática", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:49:29", :updated_at => "2013-06-26 17:49:29" },
  { :code => "201210", :name => "Diseño de una Arquitectura Web", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:49:44", :updated_at => "2013-06-26 17:49:44" },
  { :code => "201203", :name => "Datawarehouse", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:50:22", :updated_at => "2013-06-26 17:50:22" },
  { :code => "2020903", :name => "Sistemas Inteligentes", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 17:50:49", :updated_at => "2013-06-26 17:50:49" },
  { :code => "201205", :name => "E-Bussiness", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:51:13", :updated_at => "2013-06-26 17:51:13" },
  { :code => "201209", :name => "Robotica", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:51:28", :updated_at => "2013-06-26 17:51:28" },
  { :code => "202001", :name => "Algoritmica II", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:51:48", :updated_at => "2013-06-26 17:51:48" },
  { :code => "202008", :name => "Estructura de Datos", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:52:02", :updated_at => "2013-06-26 17:52:02" },
  { :code => "203001", :name => "Algoritmica III", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:52:15", :updated_at => "2013-06-26 17:52:15" },
  { :code => "203006", :name => "Diseño Grafico", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:52:32", :updated_at => "2013-06-26 17:52:32" },
  { :code => "204001", :name => "Tecnicas de Modelamiento", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:55:57", :updated_at => "2013-06-26 17:55:57" },
  { :code => "204002", :name => "Computacion Grafica", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:56:19", :updated_at => "2013-06-26 17:56:19" },
  { :code => "204008", :name => "Circuitos Digitales", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:56:37", :updated_at => "2013-06-26 17:56:37" },
  { :code => "205001", :name => "Base de Datos", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:56:58", :updated_at => "2013-06-26 17:56:58" },
  { :code => "205008", :name => "Sistemas Digitales", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:57:24", :updated_at => "2013-06-26 17:57:24" },
  { :code => "206001", :name => "Sistemas Operativos", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:57:44", :updated_at => "2013-06-26 17:57:44" },
  { :code => "207007", :name => "Diseño de Interfaz de Usuario", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:58:11", :updated_at => "2013-06-26 17:58:11" },
  { :code => "206009", :name => "Transmision de Datos", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:58:37", :updated_at => "2013-06-26 17:58:37" },
  { :code => "206010", :name => "Arquitectura de Computadoras", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:59:04", :updated_at => "2013-06-26 17:59:04" },
  { :code => "206011", :name => "Taller de Proyectos I", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:59:19", :updated_at => "2013-06-26 17:59:19" },
  { :code => "207002", :name => "Redes de Computadoras", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:59:39", :updated_at => "2013-06-26 17:59:39" },
  { :code => "207003", :name => "Diseño de Sistemas", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 17:59:56", :updated_at => "2013-06-26 17:59:56" },
  { :code => "207008", :name => "Inteligencia Artificial", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 18:00:16", :updated_at => "2013-06-26 18:00:16" },
  { :code => "207009", :name => "Modelos y Simulacion", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 18:00:31", :updated_at => "2013-06-26 18:00:37" },
  { :code => "208002", :name => "Sistemas Distribuidos", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 18:00:54", :updated_at => "2013-06-26 18:00:54" },
  { :code => "208007", :name => "Ingenieria de Software", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 18:01:13", :updated_at => "2013-06-26 18:01:13" },
  { :code => "208009", :name => "Taller de Proyectos II", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 18:01:28", :updated_at => "2013-06-26 18:01:28" },
  { :code => "208010", :name => "Ingenieria de Control", :eap_id => 1, :group_id => 1, :created_at => "2013-06-26 18:01:42", :updated_at => "2013-06-26 18:01:42" },
  { :code => "2020102", :name => "Introduccion a la computacion e Ingenieria de Software", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:02:06", :updated_at => "2013-06-26 18:02:06" },
  { :code => "2020201", :name => "Programacion I", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:02:25", :updated_at => "2013-06-26 18:02:25" },
  { :code => "2020301", :name => "Programacion II", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:02:42", :updated_at => "2013-06-26 18:02:42" },
  { :code => "2020401", :name => "Analisis y Diseño de Algoritmos", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:03:05", :updated_at => "2013-06-26 18:03:05" },
  { :code => "2020402", :name => "Estructura de Datos I", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:03:20", :updated_at => "2013-06-26 18:03:20" },
  { :code => "2020404", :name => "Sistemas Digitales", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:03:36", :updated_at => "2013-06-26 18:03:36" },
  { :code => "2020501", :name => "Base de Datos I", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:03:54", :updated_at => "2013-06-26 18:03:54" },
  { :code => "2020502", :name => "Estructura de Datos II", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:04:16", :updated_at => "2013-06-26 18:04:16" },
  { :code => "2020503", :name => "Arquitectura de Computadoras", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:04:35", :updated_at => "2013-06-26 18:04:35" },
  { :code => "2020504", :name => "Modelamiento y Requisitos de Software", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:05:02", :updated_at => "2013-06-26 18:05:02" },
  { :code => "2020601", :name => "Base de Datos II", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:05:15", :updated_at => "2013-06-26 18:05:15" },
  { :code => "2020602", :name => "Diseño de Software", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:05:36", :updated_at => "2013-06-26 18:05:36" },
  { :code => "2020604", :name => "Sistemas Operativos", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:05:57", :updated_at => "2013-06-26 18:05:57" },
  { :code => "2020701", :name => "Arquitectura de Software", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:06:15", :updated_at => "2013-06-26 18:06:15" },
  { :code => "2020702", :name => "Taller de Construccion de Software", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:06:32", :updated_at => "2013-06-26 18:06:32" },
  { :code => "2020704", :name => "Redes y Transmision de Datos", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:06:51", :updated_at => "2013-06-26 18:06:51" },
  { :code => "2020705", :name => "Gerencia de Proyectos de Software", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:07:59", :updated_at => "2013-06-26 18:07:59" },
  { :code => "2020798", :name => "E-Bussiness", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:08:17", :updated_at => "2013-06-26 18:08:17" },
  { :code => "2020799", :name => "Datawarehouse", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:08:32", :updated_at => "2013-06-26 18:08:32" },
  { :code => "2020803", :name => "Calidad de Software", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:08:48", :updated_at => "2013-06-26 18:08:48" },
  { :code => "2020804", :name => "Seguridad de Redes", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:09:03", :updated_at => "2013-06-26 18:09:03" },
  { :code => "2020901", :name => "Gestion de Configuracion y Mantenimiento", :eap_id => 2, :group_id => 1, :created_at => "2013-06-26 18:09:23", :updated_at => "2013-06-26 18:09:23" },
  { :code => "201001", :name => "Algoritmica I", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:49:08", :updated_at => "2013-06-26 17:49:08" },
  { :code => "201001", :name => "Algoritmica I", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:49:08", :updated_at => "2013-06-26 17:49:08" },
  { :code => "201001", :name => "Algoritmica I", :eap_id => 1, :group_id => 4, :created_at => "2013-06-26 17:49:08", :updated_at => "2013-06-26 17:49:08" },
  { :code => "201008", :name => "Computación Informática", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:49:29", :updated_at => "2013-06-26 17:49:29" },
  { :code => "201008", :name => "Computación Informática", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:49:29", :updated_at => "2013-06-26 17:49:29" },
  { :code => "201008", :name => "Computación Informática", :eap_id => 1, :group_id => 4, :created_at => "2013-06-26 17:49:29", :updated_at => "2013-06-26 17:49:29" },
  { :code => "201203", :name => "Datawarehouse", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:50:22", :updated_at => "2013-06-26 17:50:22" },
  { :code => "202001", :name => "Algoritmica II", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:51:48", :updated_at => "2013-06-26 17:51:48" },
  { :code => "202001", :name => "Algoritmica II", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:51:48", :updated_at => "2013-06-26 17:51:48" },
  { :code => "202008", :name => "Estructura de Datos", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:52:02", :updated_at => "2013-06-26 17:52:02" },
  { :code => "202008", :name => "Estructura de Datos", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:52:02", :updated_at => "2013-06-26 17:52:02" },
  { :code => "203001", :name => "Algoritmica III", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:52:15", :updated_at => "2013-06-26 17:52:15" },
  { :code => "203001", :name => "Algoritmica III", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:52:15", :updated_at => "2013-06-26 17:52:15" },
  { :code => "203006", :name => "Diseño Grafico", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:52:32", :updated_at => "2013-06-26 17:52:32" },
  { :code => "203006", :name => "Diseño Grafico", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:52:32", :updated_at => "2013-06-26 17:52:32" },
  { :code => "204001", :name => "Tecnicas de Modelamiento", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:55:57", :updated_at => "2013-06-26 17:55:57" },
  { :code => "204001", :name => "Tecnicas de Modelamiento", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:55:57", :updated_at => "2013-06-26 17:55:57" },
  { :code => "204002", :name => "Computacion Grafica", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:56:19", :updated_at => "2013-06-26 17:56:19" },
  { :code => "204008", :name => "Circuitos Digitales", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:56:37", :updated_at => "2013-06-26 17:56:37" },
  { :code => "204008", :name => "Circuitos Digitales", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:56:37", :updated_at => "2013-06-26 17:56:37" },
  { :code => "205001", :name => "Base de Datos", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:56:58", :updated_at => "2013-06-26 17:56:58" },
  { :code => "205001", :name => "Base de Datos", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:56:58", :updated_at => "2013-06-26 17:56:58" },
  { :code => "205008", :name => "Sistemas Digitales", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:57:24", :updated_at => "2013-06-26 17:57:24" },
  { :code => "205008", :name => "Sistemas Digitales", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:57:24", :updated_at => "2013-06-26 17:57:24" },
  { :code => "206001", :name => "Sistemas Operativos", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:57:44", :updated_at => "2013-06-26 17:57:44" },
  { :code => "206001", :name => "Sistemas Operativos", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:57:44", :updated_at => "2013-06-26 17:57:44" },
  { :code => "206001", :name => "Sistemas Operativos", :eap_id => 1, :group_id => 4, :created_at => "2013-06-26 17:57:44", :updated_at => "2013-06-26 17:57:44" },
  { :code => "207007", :name => "Diseño de Interfaz de Usuario", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:58:11", :updated_at => "2013-06-26 17:58:11" },
  { :code => "207007", :name => "Diseño de Interfaz de Usuario", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:58:11", :updated_at => "2013-06-26 17:58:11" },
  { :code => "207007", :name => "Diseño de Interfaz de Usuario", :eap_id => 1, :group_id => 4, :created_at => "2013-06-26 17:58:11", :updated_at => "2013-06-26 17:58:11" },
  { :code => "206009", :name => "Transmision de Datos", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:58:37", :updated_at => "2013-06-26 17:58:37" },
  { :code => "206009", :name => "Transmision de Datos", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:58:37", :updated_at => "2013-06-26 17:58:37" },
  { :code => "206010", :name => "Arquitectura de Computadoras", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:59:04", :updated_at => "2013-06-26 17:59:04" },
  { :code => "206010", :name => "Arquitectura de Computadoras", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:59:04", :updated_at => "2013-06-26 17:59:04" },
  { :code => "206011", :name => "Taller de Proyectos I", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:59:19", :updated_at => "2013-06-26 17:59:19" },
  { :code => "206011", :name => "Taller de Proyectos I", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:59:19", :updated_at => "2013-06-26 17:59:19" },
  { :code => "207002", :name => "Redes de Computadoras", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:59:39", :updated_at => "2013-06-26 17:59:39" },
  { :code => "207003", :name => "Diseño de Sistemas", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 17:59:56", :updated_at => "2013-06-26 17:59:56" },
  { :code => "207003", :name => "Diseño de Sistemas", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 17:59:56", :updated_at => "2013-06-26 17:59:56" },
  { :code => "207008", :name => "Inteligencia Artificial", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 18:00:16", :updated_at => "2013-06-26 18:00:16" },
  { :code => "207008", :name => "Inteligencia Artificial", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 18:00:16", :updated_at => "2013-06-26 18:00:16" },
  { :code => "207009", :name => "Modelos y Simulacion", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 18:00:31", :updated_at => "2013-06-26 18:00:37" },
  { :code => "208002", :name => "Sistemas Distribuidos", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 18:00:54", :updated_at => "2013-06-26 18:00:54" },
  { :code => "208007", :name => "Ingenieria de Software", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 18:01:13", :updated_at => "2013-06-26 18:01:13" },
  { :code => "208007", :name => "Ingenieria de Software", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 18:01:13", :updated_at => "2013-06-26 18:01:13" },
  { :code => "208009", :name => "Taller de Proyectos II", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 18:01:28", :updated_at => "2013-06-26 18:01:28" },
  { :code => "208009", :name => "Taller de Proyectos II", :eap_id => 1, :group_id => 3, :created_at => "2013-06-26 18:01:28", :updated_at => "2013-06-26 18:01:28" },
  { :code => "208010", :name => "Ingenieria de Control", :eap_id => 1, :group_id => 2, :created_at => "2013-06-26 18:01:42", :updated_at => "2013-06-26 18:01:42" },
  { :code => "2020201", :name => "Programacion I", :eap_id => 2, :group_id => 2, :created_at => "2013-06-26 18:02:25", :updated_at => "2013-06-26 18:02:25" },
  { :code => "2020301", :name => "Programacion II", :eap_id => 2, :group_id => 2, :created_at => "2013-06-26 18:02:42", :updated_at => "2013-06-26 18:02:42" },
  { :code => "2020504", :name => "Modelamiento y Requisitos de Software", :eap_id => 2, :group_id => 2, :created_at => "2013-06-26 18:05:02", :updated_at => "2013-06-26 18:05:02" },
  { :code => "2020705", :name => "Gerencia de Proyectos de Software", :eap_id => 2, :group_id => 2, :created_at => "2013-06-26 18:07:59", :updated_at => "2013-06-26 18:07:59" },
  { :code => "205006", :name => "Metodos Numericos", :eap_id => 1, :group_id => 3, :created_at => "2013-06-27 04:29:09", :updated_at => "2013-06-27 04:29:09" }
], :without_protection => true )


# encoding: utf-8

Day.create([
  { :description => "Lunes", :created_at => "2013-06-26 18:28:23", :updated_at => "2013-06-26 18:28:23" },
  { :description => "Martes", :created_at => "2013-06-26 18:28:37", :updated_at => "2013-06-26 18:28:37" },
  { :description => "Miercoles", :created_at => "2013-06-26 18:28:44", :updated_at => "2013-06-26 18:28:44" },
  { :description => "Jueves", :created_at => "2013-06-26 18:28:50", :updated_at => "2013-06-26 18:28:50" },
  { :description => "Viernes", :created_at => "2013-06-26 18:28:57", :updated_at => "2013-06-26 18:28:57" },
  { :description => "Sabado", :created_at => "2013-06-26 18:29:05", :updated_at => "2013-06-26 18:29:05" }
], :without_protection => true )


# encoding: utf-8

Eap.create([
  { :name => "Ingenieria de Sistemas", :created_at => "2013-06-26 17:46:55", :updated_at => "2013-06-26 17:46:55" },
  { :name => "Ingenieria de Software", :created_at => "2013-06-26 17:47:08", :updated_at => "2013-06-26 17:47:08" }
], :without_protection => true )


# encoding: utf-8

Group.create([
  { :name => "G1", :created_at => "2013-06-26 23:46:08", :updated_at => "2013-06-26 23:46:08" },
  { :name => "G2", :created_at => "2013-06-26 23:46:08", :updated_at => "2013-06-26 23:46:08" },
  { :name => "G3", :created_at => "2013-06-26 23:46:08", :updated_at => "2013-06-26 23:46:08" },
  { :name => "G4", :created_at => "2013-06-26 23:46:08", :updated_at => "2013-06-26 23:46:08" }
], :without_protection => true )


# encoding: utf-8

Laboratory.create([
  { :name => nil, :number => 1, :capacity => 40, :floor => 3, :numComputers => 20, :airConditioning => 1, :projector => 1, :sound => 1, :created_at => "2013-06-26 17:43:15", :updated_at => "2013-07-20 12:34:30", :user_id => 1 },
  { :name => nil, :number => 2, :capacity => 40, :floor => 3, :numComputers => 20, :airConditioning => 1, :projector => 1, :sound => 1, :created_at => "2013-06-26 17:43:37", :updated_at => "2013-07-20 07:51:15", :user_id => nil },
  { :name => nil, :number => 3, :capacity => 40, :floor => 3, :numComputers => 20, :airConditioning => 1, :projector => 1, :sound => 1, :created_at => "2013-06-26 17:43:53", :updated_at => "2013-07-20 07:55:28", :user_id => nil },
  { :name => nil, :number => 4, :capacity => 30, :floor => 3, :numComputers => 17, :airConditioning => 0, :projector => 1, :sound => 1, :created_at => "2013-06-26 17:44:14", :updated_at => "2013-06-26 17:44:14", :user_id => nil },
  { :name => nil, :number => 5, :capacity => 40, :floor => 3, :numComputers => 20, :airConditioning => 0, :projector => 1, :sound => 1, :created_at => "2013-06-26 17:44:57", :updated_at => "2013-06-26 17:44:57", :user_id => nil },
  { :name => nil, :number => 6, :capacity => 40, :floor => 3, :numComputers => 20, :airConditioning => 0, :projector => 0, :sound => 1, :created_at => "2013-06-26 17:45:15", :updated_at => "2013-06-26 17:45:15", :user_id => nil },
  { :name => nil, :number => 7, :capacity => 40, :floor => 3, :numComputers => 20, :airConditioning => 1, :projector => 1, :sound => 0, :created_at => "2013-06-26 17:45:36", :updated_at => "2013-06-26 17:45:36", :user_id => nil },
  { :name => nil, :number => 8, :capacity => 40, :floor => 1, :numComputers => 20, :airConditioning => 0, :projector => 1, :sound => 1, :created_at => "2013-06-26 17:45:52", :updated_at => "2013-06-26 17:45:52", :user_id => nil },
  { :name => nil, :number => 9, :capacity => 40, :floor => 2, :numComputers => 20, :airConditioning => 0, :projector => 1, :sound => 1, :created_at => "2013-06-26 17:46:05", :updated_at => "2013-06-26 17:46:05", :user_id => nil }
], :without_protection => true )


# encoding: utf-8

Professor.create([
  { :code => "0A1756", :name => "Albert", :lastname => "Azabache Peña", :course_id => nil, :created_at => "2013-06-26 18:09:57", :updated_at => "2013-06-26 18:09:57" },
  { :code => "018686", :name => "Augusto", :lastname => "Cortez Vasquez", :course_id => nil, :created_at => "2013-06-26 18:10:08", :updated_at => "2013-06-26 18:10:08" },
  { :code => "09831E", :name => "Cesar", :lastname => "Alcantara Loayza", :course_id => nil, :created_at => "2013-06-26 18:10:19", :updated_at => "2013-06-26 18:10:19" },
  { :code => "098329", :name => "Cesar", :lastname => "Luza Montero", :course_id => nil, :created_at => "2013-06-26 18:10:29", :updated_at => "2013-06-26 18:10:29" },
  { :code => "0A1236", :name => "Cesar", :lastname => "Molina Neyra", :course_id => 82, :created_at => "2013-06-26 18:10:41", :updated_at => "2013-06-26 18:10:41" },
  { :code => "055867", :name => "Daniel", :lastname => "Quinto Pazce", :course_id => 104, :created_at => "2013-06-26 18:10:50", :updated_at => "2013-06-26 18:10:50" },
  { :code => "083925", :name => "Dario", :lastname => "Utrilla Salazar", :course_id => nil, :created_at => "2013-06-26 18:10:59", :updated_at => "2013-06-26 18:10:59" },
  { :code => "0A0716", :name => "Fanny", :lastname => "Sobero Rodriguez", :course_id => 30, :created_at => "2013-06-26 18:11:12", :updated_at => "2013-06-26 18:11:12" },
  { :code => "099589", :name => "Felix", :lastname => "Fermin Perez", :course_id => nil, :created_at => "2013-06-26 18:11:24", :updated_at => "2013-06-26 18:11:24" },
  { :code => "088013", :name => "Ruben", :lastname => "Gil Calvo", :course_id => nil, :created_at => "2013-06-26 18:11:32", :updated_at => "2013-06-26 18:11:32" },
  { :code => "089575", :name => "Gilberto", :lastname => "Salina Azaña", :course_id => 59, :created_at => "2013-06-26 18:11:46", :updated_at => "2013-06-26 18:11:46" },
  { :code => "0A1982", :name => "Gustavo", :lastname => "Arredondo Castillo", :course_id => nil, :created_at => "2013-06-26 18:11:59", :updated_at => "2013-06-26 18:11:59" },
  { :code => "0A1874", :name => "Hugo", :lastname => "Cordero Sanchez", :course_id => nil, :created_at => "2013-06-26 18:12:13", :updated_at => "2013-06-26 18:12:13" },
  { :code => "010162", :name => "Javier", :lastname => "Cabrera Diaz", :course_id => 76, :created_at => "2013-06-26 18:12:23", :updated_at => "2013-06-26 18:12:23" },
  { :code => "09571E", :name => "Jhon", :lastname => "Trujillo Trejo", :course_id => nil, :created_at => "2013-06-26 18:12:37", :updated_at => "2013-06-26 18:12:37" },
  { :code => "097543", :name => "Jhonny", :lastname => "Avendaño Quiroz", :course_id => 13, :created_at => "2013-06-26 18:12:49", :updated_at => "2013-06-26 18:12:55" },
  { :code => "095729", :name => "Jorge", :lastname => "Chavez Soto", :course_id => nil, :created_at => "2013-06-26 18:13:06", :updated_at => "2013-06-26 18:13:06" },
  { :code => "0A1235", :name => "Jose", :lastname => "Galindo Huayllani", :course_id => nil, :created_at => "2013-06-26 18:13:19", :updated_at => "2013-06-26 18:13:19" },
  { :code => "038228", :name => "Juan", :lastname => "Gonzales Suarez", :course_id => nil, :created_at => "2013-06-26 18:13:38", :updated_at => "2013-06-26 18:13:38" },
  { :code => "0A1875", :name => "Lenis", :lastname => "Wong Portillo", :course_id => nil, :created_at => "2013-06-26 18:13:58", :updated_at => "2013-06-26 18:13:58" },
  { :code => "0A0419", :name => "Luis", :lastname => "Guerra Grados", :course_id => 52, :created_at => "2013-06-26 18:14:14", :updated_at => "2013-06-26 18:14:14" },
  { :code => "0A0397", :name => "Luis", :lastname => "Roig del Alcazar", :course_id => 50, :created_at => "2013-06-26 18:14:27", :updated_at => "2013-06-26 18:14:27" },
  { :code => "0A1232", :name => "Marco", :lastname => "Coral Ygnacio", :course_id => nil, :created_at => "2013-06-26 18:14:43", :updated_at => "2013-06-26 18:14:43" },
  { :code => "059013", :name => "Marcos", :lastname => "Rivas Peña", :course_id => nil, :created_at => "2013-06-26 18:14:53", :updated_at => "2013-06-26 18:14:53" },
  { :code => "0A0182", :name => "Maria", :lastname => "Ruiz Rivera", :course_id => 78, :created_at => "2013-06-26 18:15:06", :updated_at => "2013-06-26 18:15:06" },
  { :code => "096237", :name => "Carlos", :lastname => "Ruiz De la Cruz Melo", :course_id => nil, :created_at => "2013-06-26 18:15:22", :updated_at => "2013-06-26 18:15:22" },
  { :code => "", :name => "Michel", :lastname => "Lazaro", :course_id => nil, :created_at => "2013-06-26 18:15:33", :updated_at => "2013-06-26 18:15:33" },
  { :code => "0A1876", :name => "Sumiko", :lastname => "Murakami De la Cruz", :course_id => nil, :created_at => "2013-06-26 18:15:47", :updated_at => "2013-06-26 18:15:47" },
  { :code => "095745", :name => "Nehil", :lastname => "Muñoz Casildo", :course_id => 60, :created_at => "2013-06-26 18:15:56", :updated_at => "2013-06-26 18:15:56" },
  { :code => "088005", :name => "Nora", :lastname => "La Serna Palomino", :course_id => nil, :created_at => "2013-06-26 18:16:05", :updated_at => "2013-06-26 18:16:05" },
  { :code => "095699", :name => "Raul", :lastname => "Armas Calderon", :course_id => 19, :created_at => "2013-06-26 18:16:13", :updated_at => "2013-06-26 18:16:13" },
  { :code => "066931", :name => "Rolando", :lastname => "Solis Narro", :course_id => nil, :created_at => "2013-06-26 18:16:24", :updated_at => "2013-06-26 18:16:24" },
  { :code => "08954E", :name => "Ulises", :lastname => "Roman Concha", :course_id => nil, :created_at => "2013-06-26 18:16:37", :updated_at => "2013-06-26 18:16:37" },
  { :code => "095702", :name => "Victor", :lastname => "Bustamante Olivera", :course_id => 77, :created_at => "2013-06-26 18:16:49", :updated_at => "2013-06-26 18:16:49" },
  { :code => "085774", :name => "Virginia", :lastname => "Vera Pomalaza", :course_id => nil, :created_at => "2013-06-26 18:17:02", :updated_at => "2013-06-26 18:17:02" },
  { :code => "017779", :name => "Walter", :lastname => "Contreras Flores", :course_id => 75, :created_at => "2013-06-26 18:17:15", :updated_at => "2013-06-26 18:17:15" },
  { :code => "0A1981", :name => "Winston", :lastname => "Ugaz Cachay", :course_id => nil, :created_at => "2013-06-26 18:17:30", :updated_at => "2013-06-26 18:17:30" },
  { :code => "09756A", :name => "Zoraida", :lastname => "Mamani Rodriguez", :course_id => 36, :created_at => "2013-06-26 18:17:45", :updated_at => "2013-06-26 18:17:45" },
  { :code => "0A1871", :name => "Carlos", :lastname => "Chavez Herrera", :course_id => 5, :created_at => "2013-06-27 04:50:15", :updated_at => "2013-06-27 04:50:15" },
  { :code => "04676E", :name => "Lazaro", :lastname => "Mota Alva", :course_id => 53, :created_at => "2013-06-27 04:59:13", :updated_at => "2013-06-27 04:59:13" },
  { :code => "075825", :name => "Carlos", :lastname => "Yañez Duran", :course_id => 17, :created_at => "2013-06-27 05:01:00", :updated_at => "2013-06-27 05:01:00" },
  { :code => "0A1234", :name => "Nilo", :lastname => "Carrasco Ore", :course_id => 88, :created_at => "2013-06-27 05:02:36", :updated_at => "2013-06-27 05:02:36" },
  { :code => "09795E", :name => "Jorge", :lastname => "Diaz Muñante", :course_id => 80, :created_at => "2013-06-27 05:12:04", :updated_at => "2013-06-27 05:12:04" },
  { :code => "123", :name => "Traste", :lastname => "Intento", :course_id => nil, :created_at => "2013-07-20 09:56:48", :updated_at => "2013-07-20 09:56:48" }
], :without_protection => true )


# encoding: utf-8

Role.create([
  { :name => "Administrador", :created_at => "2013-06-28 04:07:49", :updated_at => "2013-06-28 04:07:49" },
  { :name => "Secretaria", :created_at => "2013-06-28 04:07:49", :updated_at => "2013-06-28 04:07:49" },
  { :name => "Bolsista", :created_at => "2013-06-28 04:07:49", :updated_at => "2013-06-28 04:07:49" }
], :without_protection => true )


# encoding: utf-8

Schedule.create([
  { :start => "2000-01-01 08:00:00", :end => "2000-01-01 10:00:00", :laboratory_id => 1, :course_id => 30, :day_id => 1, :created_at => "2013-06-26 20:00:55", :updated_at => "2013-06-26 20:00:55" },
  { :start => "2000-01-01 12:00:00", :end => "2000-01-01 14:00:00", :laboratory_id => 1, :course_id => 59, :day_id => 1, :created_at => "2013-06-26 20:03:01", :updated_at => "2013-06-26 20:03:12" },
  { :start => "2000-01-01 14:00:00", :end => "2000-01-01 16:00:00", :laboratory_id => 1, :course_id => 75, :day_id => 1, :created_at => "2013-06-26 20:03:28", :updated_at => "2013-06-26 20:03:28" },
  { :start => "2000-01-01 16:00:00", :end => "2000-01-01 18:00:00", :laboratory_id => 1, :course_id => 52, :day_id => 1, :created_at => "2013-06-26 20:03:43", :updated_at => "2013-06-26 20:03:43" },
  { :start => "2000-01-01 20:00:00", :end => "2000-01-01 22:00:00", :laboratory_id => 1, :course_id => 5, :day_id => 1, :created_at => "2013-06-26 20:04:16", :updated_at => "2013-06-26 20:04:16" },
  { :start => "2000-01-01 18:00:00", :end => "2000-01-01 20:00:00", :laboratory_id => 1, :course_id => 82, :day_id => 1, :created_at => "2013-06-26 20:04:28", :updated_at => "2013-06-26 20:04:36" },
  { :start => "2000-01-01 10:00:00", :end => "2000-01-01 14:00:00", :laboratory_id => 1, :course_id => 60, :day_id => 2, :created_at => "2013-06-26 20:17:28", :updated_at => "2013-06-26 20:17:28" },
  { :start => "2000-01-01 17:00:00", :end => "2000-01-01 19:00:00", :laboratory_id => 1, :course_id => 50, :day_id => 2, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 20:00:00", :end => "2000-01-01 22:00:00", :laboratory_id => 1, :course_id => 78, :day_id => 2, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 08:00:00", :end => "2000-01-01 10:00:00", :laboratory_id => 1, :course_id => 104, :day_id => 3, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 10:00:00", :end => "2000-01-01 13:00:00", :laboratory_id => 1, :course_id => 36, :day_id => 3, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 16:00:00", :end => "2000-01-01 18:00:00", :laboratory_id => 1, :course_id => 76, :day_id => 3, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 18:00:00", :end => "2000-01-01 20:00:00", :laboratory_id => 1, :course_id => 77, :day_id => 3, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 12:00:00", :end => "2000-01-01 14:00:00", :laboratory_id => 1, :course_id => 53, :day_id => 4, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 14:00:00", :end => "2000-01-01 18:00:00", :laboratory_id => 1, :course_id => 17, :day_id => 4, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 18:00:00", :end => "2000-01-01 20:00:00", :laboratory_id => 1, :course_id => 88, :day_id => 4, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 20:00:00", :end => "2000-01-01 22:00:00", :laboratory_id => 1, :course_id => 19, :day_id => 4, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 08:00:00", :end => "2000-01-01 13:00:00", :laboratory_id => 1, :course_id => 13, :day_id => 5, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" },
  { :start => "2000-01-01 14:00:00", :end => "2000-01-01 18:00:00", :laboratory_id => 1, :course_id => 80, :day_id => 5, :created_at => "2013-06-27 05:31:43", :updated_at => "2013-06-27 05:31:43" }
], :without_protection => true )


# encoding: utf-8

Software.create([
  { :name => "MySQL", :version => "5.00", :category_id => 1, :created_at => "2013-07-17 00:28:36", :updated_at => "2013-07-17 00:28:36" },
  { :name => "Oracle", :version => "6", :category_id => 1, :created_at => "2013-07-17 00:31:38", :updated_at => "2013-07-17 00:31:38" },
  { :name => "StarUML", :version => "12", :category_id => 3, :created_at => "2013-07-17 00:33:25", :updated_at => "2013-07-17 00:33:25" },
  { :name => "AutoCAD", :version => "13", :category_id => 2, :created_at => "2013-07-17 00:33:46", :updated_at => "2013-07-17 00:33:46" }
], :without_protection => true )


# encoding: utf-8

State.create([
  { :description => "En Mantenimiento", :laboratory_id => 1, :created_at => "2013-07-22 03:20:05", :updated_at => "2013-07-22 03:20:05" },
  { :description => "Libre", :laboratory_id => 2, :created_at => "2013-07-22 03:20:27", :updated_at => "2013-07-22 03:20:27" },
  { :description => "En Mantenimiento", :laboratory_id => 3, :created_at => "2013-07-22 03:20:46", :updated_at => "2013-07-22 03:20:46" },
  { :description => "En Clase", :laboratory_id => 4, :created_at => "2013-07-22 03:21:11", :updated_at => "2013-07-22 03:21:11" },
  { :description => "En Clase", :laboratory_id => 5, :created_at => "2013-07-22 03:21:20", :updated_at => "2013-07-22 03:21:20" },
  { :description => "Libre", :laboratory_id => 6, :created_at => "2013-07-22 03:21:30", :updated_at => "2013-07-22 03:21:30" },
  { :description => "En Clase", :laboratory_id => 7, :created_at => "2013-07-22 03:21:39", :updated_at => "2013-07-22 03:21:39" },
  { :description => "En Clase", :laboratory_id => 8, :created_at => "2013-07-22 03:21:51", :updated_at => "2013-07-22 03:21:51" },
  { :description => "Libre", :laboratory_id => 9, :created_at => "2013-07-22 03:22:03", :updated_at => "2013-07-22 03:22:03" }
], :without_protection => true )


# encoding: utf-8

User.create([
  { :code => "10200195", :username => "user", :name => "Usuario de Prueba", :email => "user@mail.com", :encrypted_password => "$2a$10$qNzI60tlYAJ7B8ktAGiZ1.dsG2y6mb/gU4JFziDGorl6V5P1CLBke", :role_id => 1, :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 10, :current_sign_in_at => "2013-07-22 03:24:21", :last_sign_in_at => "2013-07-22 03:19:19", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-07-20 05:08:41", :updated_at => "2013-07-22 03:24:21" },
  { :code => "10200101", :username => "user2", :name => "Secretaria", :email => "user2@mail.com", :encrypted_password => "$2a$10$TCaRDfCYHa2i5FegShPPquknCzeGVhaekiMqvLZMFEGE277hM3fli", :role_id => 3, :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => "2013-07-20 12:31:56", :updated_at => "2013-07-20 12:31:56" },
  { :code => "10200102", :username => "user3", :name => "Bolsista", :email => "user3@mail.com", :encrypted_password => "$2a$10$hQMJDrX9UEMyDFwuueTuzeGdyE3bNqwk87PW5LN4BGPHh2MZBfi0S", :role_id => 3, :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => "2013-07-20 12:32:40", :updated_at => "2013-07-20 12:32:40" }
], :without_protection => true )


